project:
  type: website
  output-dir: docs

website:
  description: "AI, Machine Learning, and Modern Tech Insights"
  site-url: https://sourangshupal.github.io
  title: "Sourangshu Pal"
  navbar:
    background: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/sourangshupal
      - icon: twitter
        href: https://twitter.com
  page-footer:
    background: dark
    left: "Â© 2025 Sourangshu Pal"
    right:
      - icon: github
        href: https://github.com/sourangshupal
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-newwindow: true



